### ISSUE TITLE
Feature Request: Split buttons to tabs/subfolders per controlled device

### ISSUE THREAD

**Issue by lucky62** [kerikun11/IR-station#7]
Hello again.
IR-station works perfectly - thanks for your effort.
I have in my living room quite lot of IR devices and I would like to control it via IR-Station.
The problem is that I have a lot of buttons. So all buttons are not on the display at the same time (need to scroll webpage) and finding the right button is not easy (e.g. I have many volume-up and volume-down buttons).

Can you please improve the firmware to better support more devices?
My idea is to organize the signals into folders (one folder per device - e.g. tv, dvd, set-top-box, amplifier, etc.)
On the generated web page the buttons can be placed on the tabs - one tab per device.
To send the signal to the device you will need to switch to the right tab (let say TV) and click the button with desired signal (let say VOLUME-UP).

I am not familiar with javascript/jquery so I can't do this by myself.

Another idea is to have the separate web-page for setup (uploading the signals) and separate page for normal usage.

Thank you in advance.

Jan

**Comment by kerikun11** [comment]
Hello, @lucky62 
I was relieved to hear that it works well.

Thank you for giving me an idea. That will contribute so much.  I think it would be nice to be able to display multiple pages.
I think it will take long time because my studies are busy, but I will consider it.
If you can improve IR-Station software, please submit pull request by all means.

Thank you.
KERI
